# Imperative
# kc secret generic <secret-name> --from-literal=key=value
# kc secret generic <secret-name> --from-file=<path-to-file>

# Declearative
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  # DB_Host: mysql
  # DB_User: root
  # DB_Password: passwrd

# This works with kc -f ./secret-data.yml
# but not safe cuz plain test
# so encode it to something liek base64 with
# echo -n "<value>" | base64 
# then the pass becomes
  DB_Host: bXlzcWw=
  DB_User: cm9vdA==
  DB_Password: cGFzc3dvcmQ=
# decode it via a simple base64 --decode