apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    component: db
spec:
  selector:
    component: db
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP        # internal only — DB should never be exposed externally