apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    name: simple-webapp
spec:
  containers:
  - name: webapp
    image: webapp
    ports:
      - containerPort: 8080

  # Will run beforehand
  initContainers:
    - name: db-checker
      image: busybox
      command:
        - 'wait-for-db-to-start.sh'