# https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/

apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - aescbc: # The primary encryption provider
          keys:
            - name: key1
              secret: <BASE64_ENCODED_32_BYTE_RANDOM_KEY>
      - identity: {} # Fallback: allows reading unencrypted data