apiVersion: v1
kind: Pod
metadata:
  name: web-pod

spec:
  # POD level
  # securityContext:
  #   runAsUser: 1000

  containers:
    - name: Ubuntu
      image: ubuntu:latest
      command: ["sleep", "4004"]

      securityContext:
        runAsUser: 1000
        capabilities: 
          add: ['NET_ADMIN']

# Docker and K8s uses linux capabilies. They can be found at
# /usr/include/linux/capability.h