apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api/
  - db/
  
# considering there are two subdirs with above
# - api/kustomization.yaml
# - api/api-depl.yaml
# - api/api-service.yaml
# - db/kustomization.yaml
# - db/db-depl.yaml
# - db/db-service.yaml
